[workspace]
resolver = "2"

members = [
    "crates/localid-identity",
    "crates/localid-credential",
    "crates/localid-session",
    "crates/localid-repository",
    "crates/localid-authentication",
    "crates/localid-storage-memory",
    "crates/localid-password",
    "crates/localid-password-argon2",
    "crates/localid-token",
]
