[workspace]
resolver = "2"

members = [
    "crates/localid-identity",
    "crates/localid-credential",
    "crates/localid-session",
    "crates/localid-repository",
    "crates/localid-authentication",
    "crates/localid-storage-memory",
    "crates/localid-password",
    "crates/localid-password-argon2",
    "crates/localid-token",
    "crates/localid-token-random",
    "crates/localid-refresh-token",
    "crates/localid-refresh-token-random",
    "crates/localid-authorization",
    "crates/localid-application",
    "crates/localid-api",
    "crates/localid-repository-memory",
    "crates/localid-role",
    "crates/localid-permission",
    "crates/localid-client",
    "crates/localid-oauth-client",
    "crates/localid-oauth-authorization",
    "crates/localid-oauth-token",
    "crates/localid-oauth",
    "crates/localid-oauth-client-repository-memory",
    "crates/localid-oauth-authorization-repository-memory",
    "crates/localid-error", "crates/localid-config",
]
