[package]
name = "localid-api"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
axum = { version = "0.8", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = "1"
tower-http = { version = "0.6", features = ["trace", "request-id"] }
tracing = "0.1"
tracing-subscriber = "0.3"

localid-application = { path = "../localid-application" }
localid-authentication = { path = "../localid-authentication" }
localid-credential = { path = "../localid-credential" }
localid-password = { path = "../localid-password" }
localid-password-argon2 = { path = "../localid-password-argon2" }
localid-repository-memory = { path = "../localid-repository-memory" }
localid-refresh-token-random = { path = "../localid-refresh-token-random" }
localid-token-random = { path = "../localid-token-random" }
localid-identity = { path = "../localid-identity" }
localid-repository = { path = "../localid-repository" }
localid-refresh-token = { path = "../localid-refresh-token" }
localid-session = { path = "../localid-session" }
localid-token = { path = "../localid-token" }
localid-authorization = { path = "../localid-authorization" }
localid-permission = { path = "../localid-permission" }
localid-role = { path = "../localid-role" }
localid-client = { path = "../localid-client" }
localid-error = { path = "../localid-error" }
localid-config = { path = "../localid-config" }
localid-crypto = { path = "../localid-crypto" }

# OAuth
localid-oauth-client = { path = "../localid-oauth-client" }
localid-oauth-client-repository-memory = { path = "../localid-oauth-client-repository-memory" }
localid-oauth-authorization = { path = "../localid-oauth-authorization" }
localid-oauth-authorization-repository-memory = { path = "../localid-oauth-authorization-repository-memory" }


[dev-dependencies]
tower = "0.5"
serde_json = "1"
http-body-util = "0.1"
base64 = "0.22"
jsonwebtoken = "9"
sha2 = "0.10"

localid-credential = { path = "../localid-credential" }
localid-identity = { path = "../localid-identity" }
localid-session = { path = "../localid-session" }
localid-token = { path = "../localid-token" }
localid-token-random = { path = "../localid-token-random" }
localid-refresh-token = { path = "../localid-refresh-token" }
localid-refresh-token-random = { path = "../localid-refresh-token-random" }
