[package]
name = "localid-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
rsa = "0.9"
rand = "0.8"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

pkcs8 = { version = "0.10", features = ["pem"] }
sha2 = { version = "0.10", features = ["oid"] }

localid-token = { path = "../localid-token" }

[dev-dependencies]
tempfile = "3"
