[package]
name = "localid-storage-memory"
version = "0.1.0"
edition = "2024"

[dependencies]
localid-credential = { path = "../localid-credential" }
localid-identity = { path = "../localid-identity" }
localid-repository = { path = "../localid-repository" }
localid-session = { path = "../localid-session" }
