[package]
name = "localid-authentication"
version = "0.1.0"
edition = "2024"

[dependencies]
localid-credential = { path = "../localid-credential" }
localid-identity = { path = "../localid-identity" }
localid-password = { version = "0.1.0", path = "../localid-password" }
localid-repository = { path = "../localid-repository" }
localid-session = { path = "../localid-session" }
localid-token = { path = "../localid-token" }
localid-token-random = { path = "../localid-token-random" }
sha2 = "0.10"
hex = "0.4"
chrono = "0.4"

[dev-dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["std"] }
localid-password-argon2 = { path = "../localid-password-argon2" }
localid-storage-memory = { path = "../localid-storage-memory" }
